services:
  web:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - ./:/app:cached
    environment:
      - PYTHONUNBUFFERED=1
      - QUART_APP=app:app
      - QUART_ENV=development
    command: python -m quart run --host 0.0.0.0 --port 8001 --reload
    env_file:
      - .env
